#!/usr/bin/env python3
"""Static-site integrity checks for the SG / Invest frontend (Sprint 7, S7.2).

Validates, over the frontend/ tree:

  (a) every asset/script/href path referenced by index.html and app.js
      resolves to an existing file, using subpath-safe relative logic
      (paths are resolved against the frontend root; root-absolute paths
      are rejected — they break under the GitHub Pages project subpath);
  (b) when frontend/data/packs/manifest.json is present it parses as JSON
      and every pack it references exists on disk (the packs directory is
      generated output and absent from a plain checkout — skipped then);
  (c) every JSON artifact under frontend/data/ (outside packs/) parses;
  (d) no link/asset reference uses a root-absolute path that would break
      under a project subpath, and styles.css keeps fonts self-hosted
      (no external @import/url; docs/data-pack-budgets.md decision).

Deliberate exceptions (documented, not drift):
  * frontend/build-info.json is generated by deploy-tier1.yml at deploy
    time; a plain checkout legitimately 404s it and app.js tolerates that.
  * `.../sg-invest-*.json` strings in app.js are user-side download=
    filenames, not fetch paths.
  * Literals containing API_BASE are adapter-mode URLs on a separately
    hosted origin, never site paths (static mode hard-guards API_BASE "").

Runs on a plain checkout with the standard library only:
    python scripts/check_static_site.py [--root frontend] [--list-paths]
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
from html.parser import HTMLParser
from pathlib import Path

ASSET_EXTENSIONS = {
    ".json", ".js", ".mjs", ".css", ".html", ".htm", ".woff2", ".woff",
    ".svg", ".png", ".jpg", ".jpeg", ".webp", ".ico", ".webmanifest", ".txt",
}
MIME_PREFIXES = ("application/", "text/", "image/", "font/", "audio/", "video/", "multipart/")
# Deploy-time generated files whose absence on a plain checkout is expected.
OPTIONAL_PATHS = {"build-info.json"}
# User-side download filenames (link.download), not fetchable site paths.
DOWNLOAD_NAME_PATTERNS = ("sg-invest-ledger.json", "sg-invest-*.json")

PATH_CHARSET = re.compile(r"^[A-Za-z0-9_./@${}*=-]+$")
QUOTED = re.compile(r""""([^"\\\n]+)"|'([^'\\\n]+)'""")
BACKTICK = re.compile(r"`([^`\n]+)`")
INTERPOLATION = re.compile(r"\$\{[^}]*\}")
URL_FUNCTION = re.compile(r"url\(\s*([^)]+?)\s*\)")
EXTERNAL_URL = re.compile(r"^https?://", re.IGNORECASE)


class SiteReferences(HTMLParser):
    """Collect src/href attribute values plus root-absolute offenders."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.references: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        for name, value in attrs:
            if name in ("src", "href") and value:
                self.references.append(value.strip())


def normalise(reference: str) -> str | None:
    """Strip query/fragment; return None for non-path references."""
    reference = reference.strip()
    if not reference or reference.startswith("#") or reference.lower().startswith(("mailto:", "tel:", "javascript:", "data:")):
        return None
    return reference.split("?", 1)[0].split("#", 1)[0]


def candidate_is_path(candidate: str) -> bool:
    if not PATH_CHARSET.match(candidate) or not candidate:
        return False
    if candidate.lower().startswith(MIME_PREFIXES) and "/" not in candidate.split("/", 1)[1]:
        return False
    # Reject non-path tokens with single-character segments (e.g. 'n/a').
    if any(len(segment) < 2 for segment in candidate.split("/")[:-1] if segment):
        return False
    if "/" in candidate:
        return True
    return candidate.lower().endswith(tuple(ASSET_EXTENSIONS))


def is_asset_like(candidate: str) -> bool:
    """True for candidates that name a site asset rather than an API fragment.

    Root-absolute references are only flagged when they look like assets
    (file extension); extension-less fragments such as '/analyze' are
    adapter-endpoint fragments consumed by apiGet, never fetched site paths.
    """
    return candidate.lower().endswith(tuple(ASSET_EXTENSIONS))


def strip_js_comments(source: str) -> str:
    # Plain checkout strings contain no 'https://' literals, so a textual
    # strip is safe here and removes quoted paths from comments.
    source = re.sub(r"/\*.*?\*/", " ", source, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", " ", source)


def literal_candidates(source: str) -> list[str]:
    """String/template literals in a JS file that look like site paths."""
    found = []
    for regex in (QUOTED, BACKTICK):
        for match in regex.finditer(strip_js_comments(source)):
            text = next(group for group in match.groups() if group is not None)
            if "API_BASE" in text:
                continue  # adapter-mode URL on another origin, never a site path
            # Validate the raw literal (the segment rule needs ${...} intact),
            # then substitute ${...} -> '*' for templated path matching.
            if candidate_is_path(text):
                found.append(INTERPOLATION.sub("*", text))
    return sorted(set(found))


def is_download_name(candidate: str) -> bool:
    return any(fnmatch.fnmatch(candidate, pattern) for pattern in DOWNLOAD_NAME_PATTERNS)


class SiteChecker:
    def __init__(self, root: Path, list_paths: bool = False) -> None:
        self.root = root
        self.list_paths = list_paths
        self.failures: list[str] = []
        self.checked_paths = 0

    def fail(self, message: str) -> None:
        self.failures.append(message)

    def resolve(self, reference: str, base: Path) -> Path | None:
        """Subpath-safe resolution: relative to `base`, never the filesystem root."""
        normalised = normalise(reference)
        if normalised is None:
            return None
        if EXTERNAL_URL.match(normalised) or normalised.startswith("//"):
            return None  # external references are allowed and never resolved
        if normalised.startswith("/"):
            if is_asset_like(normalised):
                self.fail(f"root-absolute path breaks the Pages project subpath: {reference!r} (in {base.name})")
            return None
        resolved = (base / normalised).resolve()
        root = self.root.resolve()
        if root not in resolved.parents and resolved != root:
            self.fail(f"path escapes the frontend root: {reference!r} (in {base.name})")
            return None
        return resolved

    def require_file(self, reference: str, base: Path) -> None:
        normalised = normalise(reference)
        if normalised is not None and normalised.startswith("/"):
            self.resolve(reference, base)  # root-absolute handling (extension-gated)
            return
        resolved = self.resolve(reference, base)
        if resolved is None:
            return
        rel = resolved.relative_to(self.root.resolve()).as_posix()
        if rel in OPTIONAL_PATHS or is_download_name(rel):
            print(f"  optional (may 404 by design): {rel}")
            return
        if "*" in rel:
            matches = len(list(self.root.glob(rel))) if not rel.startswith("data/packs/") or (self.root / "data/packs").is_dir() else 0
            self.checked_paths += 1
            if not matches:
                self.fail(f"no file matches templated reference {reference!r} (in {base.name}): {rel}")
            elif self.list_paths:
                print(f"  ok ({matches} match(es)): {rel}")
            return
        if rel in OPTIONAL_PATHS or is_download_name(rel):
            print(f"  optional (may 404 by design): {rel}")
            return
        self.checked_paths += 1
        if not resolved.is_file():
            self.fail(f"missing file for reference {reference!r} (in {base.name}): {rel}")
        elif self.list_paths:
            print(f"  ok: {rel}")

    def check_index_html(self) -> None:
        index = self.root / "index.html"
        if not index.is_file():
            self.fail(f"missing {index}")
            return
        parser = SiteReferences()
        parser.feed(index.read_text(encoding="utf-8"))
        print(f"index.html: {len(parser.references)} src/href reference(s)")
        for reference in parser.references:
            self.require_file(reference, self.root)

    def check_js_references(self) -> None:
        for js_name in ("app.js", "ledger-store.js"):
            js_file = self.root / js_name
            if not js_file.is_file():
                continue
            candidates = literal_candidates(js_file.read_text(encoding="utf-8"))
            print(f"{js_name}: {len(candidates)} path-like literal(s)")
            for candidate in candidates:
                self.require_file(candidate, self.root)
        # Engine modules referenced by app.js are resolved as files above; scan
        # their url()/import targets only for root-absolute breakage (d).
        for engine_file in sorted((self.root / "engine").glob("*.js")):
            for candidate in literal_candidates(engine_file.read_text(encoding="utf-8")):
                # Engine modules build pack paths against the document base;
                # only their shape is checked here (packs dir may be absent).
                if candidate.startswith(("/", "\\")):
                    self.fail(f"root-absolute path in {engine_file.name}: {candidate!r}")

    def check_styles_css(self) -> None:
        styles = self.root / "styles.css"
        if not styles.is_file():
            self.fail(f"missing {styles}")
            return
        text = styles.read_text(encoding="utf-8")
        for match in URL_FUNCTION.finditer(text):
            target = match.group(1).strip("\"' ")
            if EXTERNAL_URL.match(target) or target.startswith("//"):
                self.fail(f"external url() in styles.css breaks offline/CSP self-hosting: {target!r}")
            elif target.startswith("/"):
                self.fail(f"root-absolute url() in styles.css breaks the project subpath: {target!r}")
            elif (styles.parent / target).is_file():
                self.checked_paths += 1
                if self.list_paths:
                    print(f"  ok (styles.css): {target}")
            else:
                self.fail(f"styles.css references missing file: {target!r}")
        for line_number, line in enumerate(text.splitlines(), start=1):
            if "@import" in line and EXTERNAL_URL.search(line):
                self.fail(f"styles.css:{line_number} @imports an external stylesheet")

    def check_data_json(self) -> None:
        data_dir = self.root / "data"
        if not data_dir.is_dir():
            self.fail(f"missing {data_dir}")
            return
        json_files = sorted(path for path in data_dir.rglob("*.json") if "packs" not in path.relative_to(data_dir).parts)
        print(f"frontend/data: parsing {len(json_files)} JSON artifact(s) (packs excluded)")
        for path in json_files:
            try:
                json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError) as error:
                self.fail(f"malformed JSON artifact {path.relative_to(self.root)}: {error}")

    def check_manifest_and_packs(self) -> None:
        packs_dir = self.root / "data" / "packs"
        manifest_path = packs_dir / "manifest.json"
        if not manifest_path.is_file():
            print("frontend/data/packs: manifest absent (plain checkout) — pack existence check skipped")
            return
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as error:
            self.fail(f"malformed pack manifest: {error}")
            return
        references = [
            str((year or {}).get("pack"))
            for entry in (manifest.get("securities") or [])
            for year in (entry.get("years") or {}).values()
            if (year or {}).get("pack")
        ]
        print(f"frontend/data/packs: manifest parses; checking {len(references)} referenced pack(s)")
        missing = [pack for pack in references if not (packs_dir / pack).is_file()]
        if missing:
            self.fail(f"{len(missing)} pack(s) referenced by manifest.json are missing, e.g. {missing[:3]}")

    def run(self) -> int:
        print(f"static-site checks over {self.root}")
        self.check_index_html()
        self.check_js_references()
        self.check_styles_css()
        self.check_data_json()
        self.check_manifest_and_packs()
        if self.failures:
            print(f"\nFAILED: {len(self.failures)} problem(s)")
            for failure in self.failures:
                print(f"  - {failure}")
            return 1
        print(f"\nOK: all static-site checks passed ({self.checked_paths} file reference(s) resolved)")
        return 0


def main() -> int:
    script_root = Path(__file__).resolve().parents[1] / "frontend"
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=script_root, help=f"frontend directory (default: {script_root})")
    parser.add_argument("--list-paths", action="store_true", help="print every resolved reference")
    args = parser.parse_args()
    return SiteChecker(args.root, list_paths=args.list_paths).run()


if __name__ == "__main__":
    raise SystemExit(main())
